<script src="https://canvas-47a7.kxcdn.com/assets/js/jquery.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/bootstrap.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/material.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/jquery.easing.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/jquery.stellar.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/imagesloaded.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/jquery.countTo.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/jquery.inview.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/owl.carousel/owl.carousel.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/flexSlider/jquery.flexslider-min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/swiper.jquery.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/wow.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/material-kit.js"></script>
<script src="{{ asset('assets/js/nppy.js') }}"></script>
<script src="https://canvas-47a7.kxcdn.com/assets/js/stats.js"></script>